# Base URL used when generating links to your pages
# Set to the URL for your site
baseURL = "https://noah-ford.com"

summaryLength = 100

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "📈 Noah's Blog 💭"
author = "Noah Ford"
copyright = "Copyright © 2022, Noah Ford"
languageCode = "en-US"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy", "error-remote-getjson"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Data Stories and Other Musings"
  images = ["images/hugo-blog-og.jpeg"]
  title = "Noah's Blog"

 [markup]
  [markup.goldmark.renderer]
    unsafe=true
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 1
